### ISSUE TITLE
Polish language doesn't work

### ISSUE THREAD

**Issue by eXsio** [ca0abinary/plugin.video.jwtv-unofficial#6]
Hi

Thanks for this amazing plugin! Just wanted to report that when polish language is selected, the only menu item, that appears is 'select language'. When switching to other languages, everything seems to be working all right. Don't know is this is a temporary issue or not, but losing the ability to watch the JW Broadcasting on my raspberry pi 2 (osmc,  october update) would be very painful. 

Thanks again for great  work!

**Comment by ca0abinary** [comment]
@eXsio I'm glad you're enjoying the plugin. Could you attach your log file so I can see the error? I'm guessing it would be in the Linux location:
`$HOME/.kodi/temp/kodi.log`
but a guide to all the usual locations can be found here: http://kodi.wiki/view/Log_file/Advanced#Location

This seems similar to the issue here: https://github.com/ca0abinary/plugin.video.jwtv-unofficial/issues/5 maybe with more log files we can track down what the root cause might be.

**Comment by eXsio** [comment]
Hi

Oddly enough, it started working again. I think that there was an error on the JW.ORG side, because now, when the plugin queries http://mediator.jw.org/v1/categories/P?, it works, and before it showed 404. I think I can close this issue. If it comes up again, I'll let You know.

Thanks!

P.S.

The only things showing in Log are:
```
17:24:34 106122.867188 T:1497916448  NOTICE: -->Python Interpreter Initialized<--
17:24:35 106124.031250 T:1497916448  NOTICE: http://mediator.jw.org/v1/categories/P?
```
