### ISSUE TITLE
CEC support on Raspberry Pi

### ISSUE THREAD

**Issue by koszuf** [ca0abinary/plugin.video.jwtv-unofficial#9]
Hi,
does the plugin support the CEC protocol on Raspberry Pi? If I connect RPi to a TV, will I be able to control it using the TV remote?

thanks

**Comment by ca0abinary** [comment]
Hi @koszuf!

From what I can tell at the [Kodi Wiki for Raspberry Pi](http://kodi.wiki/view/Raspberry_Pi) the Raspberry Pi supports CEC and Kodi will handle the input as long as the keymap is configured correctly. I don't have any hardware to test on, but it looks very promising. 😄 

Please let me know if you have success.

**Comment by koszuf** [comment]
Hi,
Thanks for the answer. I'm going to buy RPi and the 'CEC issue' was the last thing to consider. As soon as I buy RPi and configure it - I'll let you know if the plugin works with a TV remote.

**Comment by joelcald** [comment]
Just chiming in as I subscribe to this thread... I use this plugin on OSMC
installed on a Raspberry Pi Zero (99 cents at MicroCenter!) and navigation
with the TV remote works flawlessly with my 6 year old Samsung TV and 2
year old Vizio TV. The Pi/osmc/CEC combination is basically seamless. Yatse
remote on android also works exceptionally well, but that's via WiFi, not
CEC.

Thanks for your great work on this plugin.


On Jan 16, 2017 3:33 PM, "Krystian" <notifications@github.com> wrote:

Hi,
Thanks for the answer. I'm going to buy RPi and the 'CEC issue' was the
last thing to consider. As soon as I buy RPi and configure it - I'll let
you know if the plugin works with a TV remote.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ca0abinary/plugin.video.jwtv-unofficial/issues/9#issuecomment-272956022>,
or mute the thread

**Comment by ca0abinary** [comment]
Looks like this issue is resolved, I'll close it. If there's anything else that needs to be done, feel free to re-open.
